version: '3.8'
services:
  web:
    build: ../apps/web
    ports:
      - "3000:3000"
  api:
    build: ../apps/api
    ports:
      - "3001:3001"
  asr:
    build: ../apps/asr
    ports:
      - "8000:8000"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
